fix: remove unused input files
NillionNetwork/nillion-python-starter pull request #14
Opened 2024-04-04 18:49 UTC by Jmgr

This removes the inputs files since we are not using them.

2024-04-04 21:17 UTC, jwolski2 requested changes
If I understand correctly, these doc updates are related to an upcoming, as of yet unreleased version of the SDK. If so, we have to hold-off on merging this until that release is properly prepped.

2024-04-05 08:07 UTC, Jmgr commented
> If I understand correctly, these doc updates are related to an upcoming, as of yet unreleased version of the SDK. If so, we have to hold-off on merging this until that release is properly prepped.

Those input files are AFAIK unused and not mentioned anywhere, so we should be fine in removing them. @oceans404 can you confirm?

2024-04-05 08:15 UTC, jimouris approved these changes

2024-04-08 21:34 UTC, oceans404 commented
yes, these are unused files and safe to remove

2024-04-08 21:34 UTC, oceans404 approved these changes

2024-04-08 21:34 UTC, merged