Restructure for DevEx
NillionNetwork/nillion-python-starter pull request #21
Opened 2024-05-01 15:41 UTC by Davetbutler

This PR sets out some structural changes in the repo to make it easier for developers to understand/use.

Setting it as a draft PR as I need to double check READMEs. I have manually tested everything. @Jmgr could you pull this branch and make sure the automated tests are passing please :)

2024-05-01 16:22 UTC, oceans404 requested changes
I like the restructure! Some of the find and replace of "permissions" => "core_concept_permissions" should stay the "permissions" since it's part of a comment, not a code path

I flagged these lines/files with "👆 permissions find and replace issue "

2024-05-01 16:22 UTC, oceans404 commented on examples_and_tutorials/millionaires_problem_example/02_store_secret_party_n.py
> +        # Give compute core_concept_permissions to Alice so she can use the secret in the specific millionionaires program by program id
looks like some comments and descriptions got included in the find and replace of permissions

2024-05-01 16:22 UTC, oceans404 commented on examples_and_tutorials/core_concept_multi_party_compute/02_store_secret_party_n.py
> +        description="Create a secret on the Nillion network with set read/retrieve core_concept_permissions"
👆 permissions find and replace issue

2024-05-01 16:23 UTC, oceans404 commented on examples_and_tutorials/core_concept_multi_party_compute/02_store_secret_party_n.py
> +        # Give compute core_concept_permissions to the first party
👆 permissions find and replace issue

2024-05-01 16:25 UTC, oceans404 reviewed
I like the restructure! Some of the find and replace of "permissions" => "core_concept_permissions" should stay the "permissions" since it's part of a comment, not a code path

I flagged some of these lines/files with "👆 permissions find and replace issue "

I think the best way to figure out how to update these is do a find and replace of " core_concept_permissions " with a space before and after the word and update back to "permissions" because these are instances where "permissions" is used in a log or comment

2024-05-01 16:25 UTC, oceans404 commented on examples_and_tutorials/core_concept_multi_party_compute/03_multi_party_compute.py
> +        description="Create a secret on the Nillion network with set read/retrieve core_concept_permissions"
👆 permissions find and replace issue

2024-05-01 16:25 UTC, oceans404 commented on examples_and_tutorials/core_concept_permissions/01_fetch_reader_userid.py
> +    print("\n\nRun the following command to store a secret and give read/retrieve core_concept_permissions to the READER USER ID")
👆 permissions find and replace issue

2024-05-01 16:25 UTC, oceans404 commented on examples_and_tutorials/core_concept_permissions/02_store_permissioned_secret.py
> +        description="Create a secret on the Nillion network with set read/retrieve core_concept_permissions"
👆 permissions find and replace issue

2024-05-01 16:25 UTC, oceans404 commented on examples_and_tutorials/core_concept_permissions/02_store_permissioned_secret.py
> +    # Writer gives themself default core_concept_permissions
👆 permissions find and replace issue

2024-05-01 16:25 UTC, oceans404 commented on examples_and_tutorials/core_concept_permissions/02_store_permissioned_secret.py
> +        raise Exception("failed to set core_concept_permissions")
👆 permissions find and replace issue

2024-05-01 16:25 UTC, oceans404 commented on examples_and_tutorials/core_concept_permissions/03_retrieve_secret.py
> +        description="Use read core_concept_permissions to retrieve a secret owned by another user on the Nillion network"
👆 permissions find and replace issue

2024-05-01 16:25 UTC, oceans404 commented on examples_and_tutorials/core_concept_permissions/03_retrieve_secret.py
> +    print("\n\nRun the following command to revoke the reader's retrieve core_concept_permissions to the secret")
👆 permissions find and replace issue

2024-05-01 16:25 UTC, oceans404 commented on examples_and_tutorials/core_concept_permissions/04_revoke_read_permissions.py
> +        description="Revoke user read/retrieve core_concept_permissions from a secret on the Nillion network"
👆 permissions find and replace issue

2024-05-01 16:27 UTC, Davetbutler commented
Thanks @oceans404, must be an over eager pycharm setting...certainly did not do this all manually! Will make sure they are changed when the PR is made properly

2024-05-03 23:36 UTC, oceans404 approved these changes
tested with https://nillion-docs-git-examples-restructure-nillion.vercel.app/

2024-05-03 23:43 UTC, merged